### ISSUE TITLE
[Web- html,css,javascript] Drag n Drop images from external storage

### ISSUE THREAD

**Issue by DevilsAutumn** [DevilsAutumn/Opensource-init#4]
**Title**
Drag n Drop images from external storage.

**Project link**
[Click here](https://github.com/DevilsAutumn/Hacktoberfest22/tree/main/Web/Html%2CCSS%2CJavascript/drag-n-drop)

**Domain**
Add 'x' inside [ ] to cross check box.

- [ ] App with Flutter
- [ ] App with Java
- [ ] App with Kotlin
- [x] Web with Html,css javascript
- [ ] Web with React

**Please describe your feature.**
In drag n drop currently we can only drag n drop image already present in the website, try to add functionality so that users can drag and drop any image they want from external storage and can delete them as well.

**Describe the solution you'd like**
NA

**Additional context**
NA

**Comment by saikatdgp2001** [comment]
Sorry to say , please don't contribute as it is excluded from Hacktoberfest 2022.

**Comment by PiyushIngale007** [comment]
Can i work on this issue?

**Comment by DevilsAutumn** [comment]
@PiyushIngale007 Sure, you can, but i hope you know this repo is not in hacktoberfest anymore.

**Comment by PiyushIngale007** [comment]
Okay. Assign this issue to me
