### ISSUE TITLE
[Web -html,css,javascript] - Improve UI of password strength background

### ISSUE THREAD

**Issue by DevilsAutumn** [DevilsAutumn/Opensource-init#45]
**Title**
Improve UI of password strength background

**Project link**
[Click here](https://github.com/DevilsAutumn/Hacktoberfest22/tree/main/Web/Html%2CCSS%2CJavascript/password-strength-background)

**Domain**
~Add 'x' inside [ ] to cross check box.~

- [ ] App with Flutter
- [ ] App with Java
- [ ] App with Kotlin
- [x] Web with Html,css javascript
- [ ] Web with React

**Describe the Issue**
Improve UI of Github profiles website according to you but it should look good. Also add screenshot of how it was before and after.

**Comment by sambhavgupta0705** [comment]
Hey can I work on this issue??

**Comment by DevilsAutumn** [comment]
Read the [Contributing guidelines.](https://github.com/DevilsAutumn/Hacktoberfest22/blob/main/CONTRIBUTIING.md) to start contributing.

**Comment by DevilsAutumn** [comment]
I have assigned it to you, you can start working on it 👍

**Comment by sambhavgupta0705** [comment]
Thanks man

**Comment by saikatdgp2001** [comment]
Sorry to say , please don't contribute as it is excluded from Hacktoberfest 2022.

**Comment by utkarshsingx** [comment]
Pls assign me this issue
